insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 31, 'tabelle', 58250, 41);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 32, 'button', 57132, 43);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 33, 'text', 20183, 45);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 34, 'text', 96861, 55);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 35, 'body', 50809, 49);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 36, 'text', 77085, 46);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 37, 'link', 95810, 48);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 38, 'titel', 76162, 60);
insert into website.navigation (navigation_type, pk_navigation_id, layout, number_of_views, fk_menu_id) values (2, 39, 'button', 12848, 45);
