INSERT INTO infom_project_4.company (pk_companyId, name, industry)
VALUES
 (1, "Homebuilding", "Hegmann-Gislason")
,(2, "Finance: Consumer Services", "Stokes, Hudson and Stark")
,(3, "n/a", "Erdman Group")
,(4, "Paper", "Labadie, Luettgen and Hayes")
,(5, "Business Services", "Pfeffer, Walker and Schinner")
,(6, "Major Chemicals", "Medhurst, Skiles and Cormier")
,(7, "Major Banks", "Lockman-Hyatt")
,(8, "n/a", "Schultz and Sons")
,(9, "Finance Companies", "Batz and Sons")
,(10, "Major Pharmaceuticals", "Sauer-Reilly")
,(11, "Oil & Gas Production", "Halvorson Group")
,(12, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Bogisich-Zemlak")
,(13, "Property-Casualty Insurers", "Dickinson-Ratke")
,(14, "Computer Software: Prepackaged Software", "Graham, Anderson and Bartoletti")
,(15, "Life Insurance", "Ebert Group")
,(16, "EDP Services", "Okuneva and Sons")
,(17, "Real Estate", "Luettgen, Brekke and Wuckert")
,(18, "Steel/Iron Ore", "Fisher, Heaney and Veum")
,(19, "Telecommunications Equipment", "Hessel, Gottlieb and Morissette")
,(20, "Paints/Coatings", "Wilkinson-Oberbrunner")
,(21, "Savings Institutions", "Corwin-Sauer")
,(22, "Rental/Leasing Companies", "Stehr, Jacobi and Baumbach")
,(23, "Semiconductors", "Durgan, Wyman and Ritchie")
,(24, "Industrial Specialties", "Wisoky and Sons")
,(25, "Business Services", "Prosacco, Rutherford and Oberbrunner")
,(26, "Oil & Gas Production", "Effertz Group")
,(27, "Services-Misc. Amusement & Recreation", "Klocko Inc")
,(28, "Major Pharmaceuticals", "Wiegand, Smitham and Heathcote")
,(29, "Medical/Nursing Services", "Corwin, Jaskolski and Bode")
,(30, "Hotels/Resorts", "Reichel Group")
,(31, "n/a", "Littel-Kilback")
,(32, "Containers/Packaging", "Wiegand, Swaniawski and Brekke")
,(33, "n/a", "Upton Inc")
,(34, "Industrial Machinery/Components", "Rowe, Jast and Simonis")
,(35, "n/a", "Wisozk Inc")
,(36, "n/a", "Mertz LLC")
,(37, "Finance: Consumer Services", "Kutch-O'Connell")
,(38, "Metal Fabrications", "Gutmann, Effertz and Dare")
,(39, "Major Banks", "Schuster Group")
,(40, "n/a", "Prohaska, Fadel and Gleason")
,(41, "Major Banks", "Willms, Botsford and Denesik")
,(42, "Natural Gas Distribution", "Dach, Heaney and Bartoletti")
,(43, "Computer Software: Prepackaged Software", "Roberts-Lindgren")
,(44, "Major Pharmaceuticals", "Zieme, Stokes and Rolfson")
,(45, "RETAIL: Building Materials", "Kreiger-Jones")
,(46, "n/a", "Dickinson, Halvorson and Bechtelar")
,(47, "Major Pharmaceuticals", "Abbott Inc")
,(48, "Industrial Specialties", "Monahan-Altenwerth")
,(49, "Business Services", "O'Keefe-Goodwin")
,(50, "n/a", "Hintz-Okuneva")
,(51, "Real Estate", "Erdman-Medhurst")
,(52, "Paper", "Kirlin-Jones")
,(53, "Real Estate Investment Trusts", "Towne-Lockman")
,(54, "Business Services", "Bednar, Considine and Paucek")
,(55, "Semiconductors", "Schneider and Sons")
,(56, "Home Furnishings", "Weber-Von")
,(57, "Investment Bankers/Brokers/Service", "Marquardt, Donnelly and Stiedemann")
,(58, "Computer Software: Prepackaged Software", "Leffler-Cummings")
,(59, "Major Pharmaceuticals", "Hoeger Inc")
,(60, "Major Banks", "Bergnaum, Hackett and Runte")
,(61, "Other Consumer Services", "Berge, Ratke and Kub")
,(62, "Electric Utilities: Central", "Bogan, Hegmann and Brown")
,(63, "Oil & Gas Production", "Mertz, Rau and Auer")
,(64, "Oil & Gas Production", "Oberbrunner-Ebert")
,(65, "Oil & Gas Production", "Yundt-Marvin")
,(66, "Telecommunications Equipment", "Feil Inc")
,(67, "Major Pharmaceuticals", "Wyman Inc")
,(68, "Computer Software: Programming, Data Processing", "Bergstrom-Mosciski")
,(69, "Restaurants", "Rosenbaum, Sipes and Simonis")
,(70, "n/a", "Gibson, Mosciski and Kertzmann")
,(71, "n/a", "Nitzsche Group")
,(72, "n/a", "Runolfsdottir LLC")
,(73, "n/a", "Paucek-Buckridge")
,(74, "Property-Casualty Insurers", "Steuber, Tillman and Larkin")
,(75, "Advertising", "Waters, Price and Weimann")
,(76, "n/a", "Bruen-Schiller")
,(77, "n/a", "Hodkiewicz, Parisian and Gottlieb")
,(78, "n/a", "Schneider, Adams and Ondricka")
,(79, "Major Banks", "Reinger-Borer")
,(80, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Torp Inc")
,(81, "n/a", "Rosenbaum and Sons")
,(82, "n/a", "McClure-Borer")
,(83, "Specialty Chemicals", "Kunde, Williamson and Kris")
,(84, "Precious Metals", "O'Conner Inc")
,(85, "n/a", "Volkman-Schuster")
,(86, "Marine Transportation", "Grady-Pfeffer")
,(87, "Marine Transportation", "Auer-Dicki")
,(88, "n/a", "Mills, Pollich and Kirlin")
,(89, "Medical/Nursing Services", "Roob-Hammes")
,(90, "Medical/Dental Instruments", "Bruen Inc")
,(91, "Real Estate Investment Trusts", "Borer Inc")
,(92, "Marine Transportation", "Harris-Goodwin")
,(93, "n/a", "Predovic Inc")
,(94, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Upton, Gottlieb and Collins")
,(95, "n/a", "Barton-Cummings")
,(96, "Real Estate Investment Trusts", "Braun Group")
,(97, "Department/Specialty Retail Stores", "Rosenbaum-Bailey")
,(98, "Military/Government/Technical", "Moore-Mante")
,(99, "n/a", "Kautzer Inc")
,(100, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Skiles Inc")
,(101, "Real Estate Investment Trusts", "Padberg Inc")
,(102, "Integrated oil Companies", "Mosciski LLC")
,(103, "Professional Services", "Sanford-Boyer")
,(104, "Computer Software: Prepackaged Software", "Rohan Group")
,(105, "n/a", "Hagenes, Douglas and Jacobson")
,(106, "Biotechnology: Commercial Physical & Biological Resarch", "Cummerata, Witting and Corwin")
,(107, "Finance: Consumer Services", "Yost, Schultz and Lind")
,(108, "n/a", "O'Conner LLC")
,(109, "Advertising", "Green-Upton")
,(110, "Major Pharmaceuticals", "Flatley, Schulist and Streich")
,(111, "Apparel", "Gerlach Group")
,(112, "n/a", "Shanahan, Durgan and Lockman")
,(113, "Semiconductors", "Bins, Medhurst and Hansen")
,(114, "Business Services", "Goldner-Block")
,(115, "Beverages (Production/Distribution)", "Pollich Inc")
,(116, "Major Pharmaceuticals", "Kub Group")
,(117, "Major Pharmaceuticals", "Cassin and Sons")
,(118, "Other Specialty Stores", "Ankunding-Price")
,(119, "Major Pharmaceuticals", "McLaughlin LLC")
,(120, "Marine Transportation", "Cummerata-Wisozk")
,(121, "n/a", "Bartoletti, O'Keefe and Windler")
,(122, "Oil/Gas Transmission", "Metz, Altenwerth and Labadie")
,(123, "Home Furnishings", "Abbott, Schulist and Kovacek")
,(124, "Computer Software: Programming, Data Processing", "Anderson Inc")
,(125, "Precious Metals", "Runte-Cruickshank")
,(126, "n/a", "Schoen, King and Koepp")
,(127, "n/a", "Harvey and Sons")
,(128, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Mann-Schaden")
,(129, "Broadcasting", "Rice LLC")
,(130, "Other Consumer Services", "Morissette-Doyle")
,(131, "Mining & Quarrying of Nonmetallic Minerals (No Fuels)", "Hoeger LLC")
,(132, "Marine Transportation", "Jacobson Inc")
,(133, "Other Consumer Services", "Carter Inc")
,(134, "Major Chemicals", "Becker-Stokes")
,(135, "EDP Services", "Marquardt, Lesch and Veum")
,(136, "Medical/Dental Instruments", "Oberbrunner, Hamill and Fisher")
,(137, "Oil & Gas Production", "Ferry, Marks and Purdy")
,(138, "n/a", "Bogan Group")
,(139, "Industrial Specialties", "Abbott, Gutkowski and Beer")
,(140, "Major Pharmaceuticals", "Gleason-Corkery")
,(141, "Major Banks", "Hettinger-Hessel")
,(142, "Savings Institutions", "McClure Inc")
,(143, "Major Pharmaceuticals", "Greenholt, Block and Fisher")
,(144, "Major Banks", "Turcotte-Ebert")
,(145, "n/a", "Bergnaum Group")
,(146, "Medical/Dental Instruments", "Hayes-Rempel")
,(147, "Biotechnology: Biological Products (No Diagnostic Substances)", "Schimmel, Bogisich and Krajcik")
,(148, "Oil & Gas Production", "Nader, Schultz and Berge")
,(149, "Semiconductors", "Swaniawski, Runolfsdottir and Bahringer")
,(150, "Business Services", "Hamill Group")
,(151, "Business Services", "Kassulke LLC")
,(152, "Investment Managers", "Olson, Bartell and Mosciski")
,(153, "Precious Metals", "Prosacco-Hane")
,(154, "Major Banks", "Hayes LLC")
,(155, "Computer Software: Prepackaged Software", "Sipes Inc")
,(156, "Savings Institutions", "Lehner LLC")
,(157, "Packaged Foods", "Hirthe, Schumm and Legros")
,(158, "Computer Software: Programming, Data Processing", "Mitchell-Schaefer")
,(159, "Military/Government/Technical", "Bailey, Swaniawski and Schumm")
,(160, "Major Chemicals", "Crona-Prohaska")
,(161, "EDP Services", "Ruecker-Grady")
,(162, "Engineering & Construction", "Luettgen, Ziemann and Abshire")
,(163, "Computer Software: Prepackaged Software", "Legros-Oberbrunner")
,(164, "Medical Specialities", "Hayes, Schulist and Gibson")
,(165, "Major Banks", "Bernier, Bartell and Herman")
,(166, "Life Insurance", "Douglas Group")
,(167, "Oil & Gas Production", "O'Hara-Larkin")
,(168, "n/a", "Hintz Group")
,(169, "Computer Software: Prepackaged Software", "Waters Group")
,(170, "n/a", "Breitenberg, Schaden and Farrell")
,(171, "n/a", "Hermiston-Kuhlman")
,(172, "Industrial Machinery/Components", "Ryan, Herman and Frami")
,(173, "Real Estate Investment Trusts", "Hintz-Cole")
,(174, "Industrial Machinery/Components", "Bartell-Dietrich")
,(175, "Oil & Gas Production", "Feeney Group")
,(176, "Marine Transportation", "Batz, Bednar and Lockman")
,(177, "Metal Fabrications", "Fadel Inc")
,(178, "Major Banks", "Zieme, Rolfson and Beahan")
,(179, "Finance: Consumer Services", "Champlin Group")
,(180, "Industrial Specialties", "Dickens and Sons")
,(181, "Metal Fabrications", "Daugherty Group")
,(182, "Investment Managers", "O'Kon-Anderson")
,(183, "Home Furnishings", "Gusikowski and Sons")
,(184, "Real Estate", "Quigley-Towne")
,(185, "Semiconductors", "Kuhn LLC")
,(186, "n/a", "Gleason and Sons")
,(187, "n/a", "Hagenes-Morissette")
,(188, "Oil & Gas Production", "Turcotte-Stamm")
,(189, "Telecommunications Equipment", "Moen, Rowe and Rosenbaum")
,(190, "Department/Specialty Retail Stores", "Pouros LLC")
,(191, "Biotechnology: Laboratory Analytical Instruments", "Will Group")
,(192, "Telecommunications Equipment", "Sipes, Harber and Beer")
,(193, "n/a", "Stamm-Weissnat")
,(194, "n/a", "Howell LLC")
,(195, "n/a", "Bartell and Sons")
,(196, "Packaged Foods", "Padberg, Marquardt and Bosco")
,(197, "Shoe Manufacturing", "Simonis Group")
,(198, "Auto Manufacturing", "Cruickshank Group")
,(199, "n/a", "Farrell-Cole")
,(200, "Electric Utilities: Central", "Hahn-Jacobi")
,(201, "Major Chemicals", "Rohan LLC")
,(202, "Major Chemicals", "Daugherty-Erdman")
,(203, "n/a", "Abshire, Roob and Cole")
,(204, "Biotechnology: In Vitro & In Vivo Diagnostic Substances", "Witting Inc")
,(205, "Computer Software: Prepackaged Software", "Senger, Welch and Dickens")
,(206, "n/a", "Kutch-Bins")
,(207, "n/a", "Schaefer, Hackett and Durgan")
,(208, "Multi-Sector Companies", "Abshire, Wolf and Luettgen")
,(209, "n/a", "Kub, Kunde and Gorczany")
,(210, "Major Chemicals", "Boehm, Boyer and Reichel")
,(211, "Property-Casualty Insurers", "Schuster-Runte")
,(212, "n/a", "Goodwin, Ankunding and Waters")
,(213, "Biotechnology: In Vitro & In Vivo Diagnostic Substances", "Cummerata, Hickle and Ritchie")
,(214, "Computer Software: Prepackaged Software", "Morar, Senger and Koss")
,(215, "Real Estate", "Gusikowski, Wunsch and Marks")
,(216, "Industrial Machinery/Components", "Stracke, Effertz and Pfeffer")
,(217, "Life Insurance", "Rutherford Inc")
,(218, "Precious Metals", "Gusikowski, Konopelski and Paucek")
,(219, "Semiconductors", "Green LLC")
,(220, "Biotechnology: Biological Products (No Diagnostic Substances)", "Skiles-Oberbrunner")
,(221, "n/a", "Bogan-Swift")
,(222, "Oil & Gas Production", "Reilly-Haley")
,(223, "Property-Casualty Insurers", "Hermann, Doyle and Funk")
,(224, "n/a", "Donnelly, Haley and Schultz")
,(225, "Major Pharmaceuticals", "Trantow and Sons")
,(226, "Environmental Services", "O'Hara LLC")
,(227, "Commercial Banks", "Kris-Blanda")
,(228, "Medical/Dental Instruments", "Hahn-Heathcote")
,(229, "Industrial Machinery/Components", "Kunze, Hills and Streich")
,(230, "Medical Specialities", "Abernathy Inc")
,(231, "Steel/Iron Ore", "Volkman Group")
,(232, "Real Estate Investment Trusts", "Hessel-Lowe")
,(233, "n/a", "Dicki Group")
,(234, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Schumm, Kuhic and Thiel")
,(235, "Medical Electronics", "Hackett, O'Conner and Lakin")
,(236, "n/a", "Lebsack LLC")
,(237, "Shoe Manufacturing", "Tromp Inc")
,(238, "Medical Specialities", "Reichel and Sons")
,(239, "Computer Software: Prepackaged Software", "Daniel-Klocko")
,(240, "n/a", "Tremblay LLC")
,(241, "Industrial Machinery/Components", "Keeling Inc")
,(242, "Major Banks", "Kihn, Lindgren and Rohan")
,(243, "n/a", "Rice, Rowe and Rolfson")
,(244, "Major Banks", "Franecki-Smith")
,(245, "Apparel", "Kuhlman-Volkman")
,(246, "Real Estate Investment Trusts", "Wunsch, Graham and King")
,(247, "RETAIL: Building Materials", "Langworth, Koch and Wyman")
,(248, "n/a", "Johnson LLC")
,(249, "Consumer Specialties", "Franecki, Tromp and Hermann")
,(250, "Electric Utilities: Central", "Williamson Group")
,(251, "Medical/Dental Instruments", "Veum-Schoen")
,(252, "n/a", "Lakin and Sons")
,(253, "Electrical Products", "Hane, Braun and Quigley")
,(254, "Major Pharmaceuticals", "Rempel, Paucek and Lind")
,(255, "Computer Software: Programming, Data Processing", "Kris and Sons")
,(256, "Major Banks", "Rolfson and Sons")
,(257, "Oil & Gas Production", "Dach-Oberbrunner")
,(258, "Biotechnology: Commercial Physical & Biological Resarch", "Hills Group")
,(259, "n/a", "Bogan-Kilback")
,(260, "n/a", "Schmitt-Farrell")
,(261, "Biotechnology: Biological Products (No Diagnostic Substances)", "Tillman-Abbott")
,(262, "Specialty Insurers", "Keebler, Larson and Torphy")
,(263, "Metal Fabrications", "Hamill-Bayer")
,(264, "Fluid Controls", "Ritchie Group")
,(265, "Professional Services", "Sipes, Torphy and Moore")
,(266, "Oilfield Services/Equipment", "Jakubowski-Runolfsdottir")
,(267, "Major Banks", "Grant, Fay and Volkman")
,(268, "Computer Software: Prepackaged Software", "Tillman-Runolfsdottir")
,(269, "n/a", "Schultz, Beatty and Windler")
,(270, "Oil & Gas Production", "Medhurst Inc")
,(271, "Engineering & Construction", "Ferry-Ortiz")
,(272, "n/a", "Stracke Group")
,(273, "Telecommunications Equipment", "Conroy-Kuhic")
,(274, "Hotels/Resorts", "Raynor, Farrell and DuBuque")
,(275, "Medical/Dental Instruments", "Kautzer, Langworth and Bernhard")
,(276, "Real Estate Investment Trusts", "Morar LLC")
,(277, "Diversified Financial Services", "Moore, Wiegand and Greenholt")
,(278, "Semiconductors", "Howell-Johnson")
,(279, "n/a", "Anderson-Grant")
,(280, "Industrial Specialties", "Spinka LLC")
,(281, "Medical/Dental Instruments", "Koepp and Sons")
,(282, "n/a", "Smith-Bartell")
,(283, "Telecommunications Equipment", "Mayert, Batz and Wuckert")
,(284, "Industrial Specialties", "Bashirian, Waelchi and Crist")
,(285, "Biotechnology: Biological Products (No Diagnostic Substances)", "Schinner, Koss and Kohler")
,(286, "Specialty Foods", "Bailey-Macejkovic")
,(287, "Business Services", "Mohr, Lubowitz and Beahan")
,(288, "Property-Casualty Insurers", "Moore Inc")
,(289, "Biotechnology: Biological Products (No Diagnostic Substances)", "Shanahan-Lowe")
,(290, "Major Banks", "Rosenbaum-Davis")
,(291, "n/a", "Wolf Inc")
,(292, "n/a", "Huel LLC")
,(293, "Steel/Iron Ore", "Upton, Jenkins and Krajcik")
,(294, "Other Consumer Services", "Reilly, Powlowski and Wehner")
,(295, "Business Services", "McLaughlin-Towne")
,(296, "Precious Metals", "Blanda-Volkman")
,(297, "Major Pharmaceuticals", "Stoltenberg-Lind")
,(298, "Other Specialty Stores", "Cummerata LLC")
,(299, "Telecommunications Equipment", "O'Reilly, Wyman and Kris")
,(300, "Recreational Products/Toys", "Buckridge LLC")
,(301, "Specialty Chemicals", "Aufderhar-Ritchie")
,(302, "Semiconductors", "Wilderman and Sons")
,(303, "Pollution Control Equipment", "Hand LLC")
,(304, "Agricultural Chemicals", "Jacobs, Langworth and Kohler")
,(305, "Business Services", "Price Group")
,(306, "Industrial Machinery/Components", "Johnson-Franecki")
,(307, "Medical Specialities", "Osinski, Smith and Upton")
,(308, "Business Services", "Bergnaum Inc")
,(309, "Oil & Gas Production", "DuBuque-Pfannerstill")
,(310, "Coal Mining", "Keebler-Hilpert")
,(311, "Hospital/Nursing Management", "Monahan, Zboncak and Towne")
,(312, "Commercial Banks", "Hessel-Carroll")
,(313, "Major Banks", "Friesen, Anderson and Greenfelder")
,(314, "Medical/Dental Instruments", "Graham LLC")
,(315, "n/a", "Olson LLC")
,(316, "n/a", "Wiegand-Bartell")
,(317, "n/a", "Roberts Inc")
,(318, "Major Banks", "Welch, Pacocha and Haley")
,(319, "Restaurants", "Baumbach-Walter")
,(320, "Restaurants", "Moore, Heaney and Considine")
,(321, "Other Consumer Services", "Quigley, Ortiz and Smith")
,(322, "Business Services", "Deckow-Williamson")
,(323, "Professional Services", "Oberbrunner, Rippin and Murphy")
,(324, "Major Banks", "O'Reilly-Bailey")
,(325, "Computer Manufacturing", "Kuphal-Kshlerin")
,(326, "Savings Institutions", "Dicki-Ondricka")
,(327, "Major Banks", "Jakubowski, Smitham and Stroman")
,(328, "Business Services", "Hills Inc")
,(329, "Major Pharmaceuticals", "Schmitt, Harber and Emmerich")
,(330, "Major Pharmaceuticals", "Jacobson and Sons")
,(331, "n/a", "Pouros Inc")
,(332, "Business Services", "Hyatt, Jacobson and Dietrich")
,(333, "Major Pharmaceuticals", "Walsh, Bergnaum and Bogisich")
,(334, "Automotive Aftermarket", "Leuschke-Larson")
,(335, "Hotels/Resorts", "Nienow, Beahan and Bernhard")
,(336, "n/a", "Konopelski-Metz")
,(337, "Banks", "Kohler, Bartell and Bosco")
,(338, "Integrated oil Companies", "Schulist, Shanahan and Flatley")
,(339, "Marine Transportation", "Douglas and Sons")
,(340, "Apparel", "Tillman-Towne")
,(341, "Office Equipment/Supplies/Services", "O'Connell LLC")
,(342, "Electrical Products", "Buckridge, Dickens and Gutkowski")
,(343, "Finance/Investors Services", "Quigley Inc")
,(344, "Medical Electronics", "Hayes-Anderson")
,(345, "Major Pharmaceuticals", "Gusikowski-Sipes")
,(346, "n/a", "Lynch, Heaney and Russel")
,(347, "Advertising", "Homenick, Leuschke and Runolfsson")
,(348, "Oil/Gas Transmission", "Jaskolski-Murphy")
,(349, "Packaged Foods", "Osinski, Blanda and Rodriguez")
,(350, "Automotive Aftermarket", "Spinka Group")
,(351, "n/a", "Hudson LLC")
,(352, "Ordnance And Accessories", "Braun-Gulgowski")
,(353, "Major Pharmaceuticals", "Stiedemann, Fisher and Ratke")
,(354, "Diversified Commercial Services", "Stoltenberg, Walter and Franecki")
,(355, "n/a", "Keebler Inc")
,(356, "n/a", "Cummerata Group")
,(357, "EDP Services", "Ondricka-Christiansen")
,(358, "Apparel", "Ferry LLC")
,(359, "Savings Institutions", "Hoppe, Volkman and Marquardt")
,(360, "n/a", "Ankunding-Abshire")
,(361, "Medical/Dental Instruments", "Medhurst-Daugherty")
,(362, "Electric Utilities: Central", "Towne and Sons")
,(363, "n/a", "Braun, Goyette and O'Conner")
,(364, "n/a", "Cruickshank Group")
,(365, "Water Supply", "Mann-Toy")
,(366, "Radio And Television Broadcasting And Communications Equipment", "Upton-Kunze")
,(367, "Military/Government/Technical", "Bergstrom, Willms and Terry")
,(368, "Medical/Dental Instruments", "Hickle-Keebler")
,(369, "n/a", "Toy-Haag")
,(370, "Services-Misc. Amusement & Recreation", "Kozey and Sons")
,(371, "Power Generation", "Kovacek, Bogan and Mueller")
,(372, "Environmental Services", "Lockman, Morissette and Zulauf")
,(373, "Natural Gas Distribution", "Herzog Inc")
,(374, "Industrial Machinery/Components", "Wisozk, Kessler and Schultz")
,(375, "n/a", "Carter-Kris")
,(376, "n/a", "Marks, Beier and Durgan")
,(377, "Investment Bankers/Brokers/Service", "Moen, Franecki and McClure")
,(378, "Computer Software: Prepackaged Software", "Funk, Bauch and Davis")
,(379, "Major Banks", "Maggio-Dickens")
,(380, "Major Pharmaceuticals", "Buckridge, Oberbrunner and Marks")
,(381, "Professional Services", "McKenzie, Wiza and Weissnat")
,(382, "Specialty Chemicals", "Herman-Bayer")
,(383, "EDP Services", "Miller, Willms and Wilkinson")
,(384, "Electronic Components", "Lynch and Sons")
,(385, "n/a", "Becker-Walter")
,(386, "Building Products", "Koch-Effertz")
,(387, "n/a", "Prohaska-Farrell")
,(388, "Major Banks", "D'Amore, Witting and Tremblay")
,(389, "Industrial Specialties", "Gusikowski-Wolff")
,(390, "Home Furnishings", "Mante-Lueilwitz")
,(391, "Medical Specialities", "Hegmann Inc")
,(392, "Steel/Iron Ore", "Cartwright LLC")
,(393, "Biotechnology: Biological Products (No Diagnostic Substances)", "Tromp, Reilly and Murazik")
,(394, "Mining & Quarrying of Nonmetallic Minerals (No Fuels)", "Leffler Inc")
,(395, "Major Chemicals", "Lang Inc")
,(396, "Real Estate", "Padberg-Towne")
,(397, "Beverages (Production/Distribution)", "Trantow-Crona")
,(398, "Property-Casualty Insurers", "Kautzer and Sons")
,(399, "Major Banks", "Bashirian, Swaniawski and Harber")
,(400, "Major Banks", "Nolan LLC")
,(401, "Natural Gas Distribution", "Johnson Inc")
,(402, "n/a", "Klein LLC")
,(403, "Professional Services", "Graham, Carter and Jast")
,(404, "Hotels/Resorts", "Becker, Hills and Turcotte")
,(405, "EDP Services", "Wolf Group")
,(406, "Shoe Manufacturing", "Batz-Mraz")
,(407, "Real Estate Investment Trusts", "Gleichner Inc")
,(408, "n/a", "Smith Group")
,(409, "n/a", "Cummings, O'Kon and Botsford")
,(410, "Containers/Packaging", "Von LLC")
,(411, "n/a", "Green Inc")
,(412, "Property-Casualty Insurers", "Durgan-Howe")
,(413, "Automotive Aftermarket", "Mueller, Collins and Wilderman")
,(414, "Commercial Banks", "Johnston, Kuhic and Davis")
,(415, "Real Estate Investment Trusts", "Muller, Hermiston and Johnston")
,(416, "n/a", "Breitenberg-Stiedemann")
,(417, "Real Estate Investment Trusts", "Gutmann, Witting and Homenick")
,(418, "n/a", "Halvorson LLC")
,(419, "Real Estate Investment Trusts", "Kulas and Sons")
,(420, "Oil & Gas Production", "Muller-Fritsch")
,(421, "Business Services", "Simonis Inc")
,(422, "n/a", "Klein, Bogisich and Jacobson")
,(423, "Major Banks", "Kub-Feest")
,(424, "n/a", "Crist-Daniel")
,(425, "Major Pharmaceuticals", "Rempel, Lueilwitz and Gutkowski")
,(426, "n/a", "Gleichner, Dare and Bergnaum")
,(427, "Computer Software: Prepackaged Software", "Greenfelder-Welch")
,(428, "Medical/Nursing Services", "Larson, Johns and Bashirian")
,(429, "Commercial Banks", "Bogan, Emard and Lockman")
,(430, "Major Pharmaceuticals", "Beahan and Sons")
,(431, "Biotechnology: Electromedical & Electrotherapeutic Apparatus", "Lubowitz-Corkery")
,(432, "Real Estate Investment Trusts", "Shields-Moen")
,(433, "n/a", "Jacobs, Zemlak and Sporer")
,(434, "Power Generation", "Hamill-Schaefer")
,(435, "Semiconductors", "Erdman LLC")
,(436, "Real Estate Investment Trusts", "Hahn Group")
,(437, "n/a", "O'Reilly Inc")
,(438, "Oil & Gas Production", "Paucek, Daniel and Huel")
,(439, "Investment Managers", "Orn, Morar and Labadie")
,(440, "n/a", "Kshlerin and Sons")
,(441, "n/a", "Rohan-Boyle")
,(442, "n/a", "Ferry-Mante")
,(443, "Major Banks", "Baumbach, Barrows and Gottlieb")
,(444, "Property-Casualty Insurers", "Gottlieb-Hartmann")
,(445, "Major Pharmaceuticals", "Schowalter-Johnston")
,(446, "Industrial Specialties", "Carter LLC")
,(447, "n/a", "Tremblay, Halvorson and Bahringer")
,(448, "Major Banks", "Bins-Tremblay")
,(449, "n/a", "Harber-Sauer")
,(450, "Industrial Machinery/Components", "Feil, Swift and Funk")
;